dist: trusty
sudo: false
language: php
php:
  - '7.1'

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - npm install -g sloc@latest
  - cp .env.travis .env
  - mysql -u root -e 'create database `docspen-test`;'
  - mysql -u root -e "CREATE USER 'docspen-test'@'localhost' IDENTIFIED BY 'docspen-test';"
  - mysql -u root -e "GRANT ALL ON \`docspen-test\`.* TO 'docspen-test'@'localhost';"
  - mysql -u root -e "FLUSH PRIVILEGES;"
  - phpenv config-rm xdebug.ini
  - composer install --prefer-dist --no-interaction
  - php artisan clear-compiled -n
  - php artisan optimize -n
  - php artisan migrate --force -n --database=mysql_testing
  - php artisan db:seed --force -n --class=DummyContentSeeder --database=mysql_testing

after_failure:
  - cat storage/logs/laravel.log

script:
  - sloc .
  
notifications:
  webhooks:
    urls:
      - https://integrations.bonbotics.io/travis/webhook/aRbJVCgYFSel7wtydqkqp0yPNFayUgfujMr6mILMJUs
    on_success: change # default: always
    on_failure: always # default: always
    on_start: change   # default: never
    on_cancel: always # default: always
    on_error: always # default: always
